default: &default
  adapter: postgresql
  encoding: unicode
  pool: 30

development:
  <<: *default
  url: <%= Rails.application.credentials.database_url %>

test:
  <<: *default
  url: <%= ENV["DATABASE_URL"] || Rails.application.credentials.database_url %>
  gssencmode: disable

production:
  <<: *default
  url: <%= Rails.application.credentials.database_url %>
