default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= Rails.application.credentials.database_url %>

test:
  <<: *default
  url: <%= Rails.application.credentials.database_url %>
  gssencmode: disable

production:
  <<: *default
  url: <%= Rails.application.credentials.database_url %>
