service: rubycrow
image: k0va1/rubycrow

ssh:
  user: www

registry:
  server: "localhost:5555"

builder:
  arch: amd64
  args:
    RUBY_VERSION: "4.0.1"
    NODE_VERSION: "25.2.1"
    YARN_VERSION: "1.22.22"
    RAILS_ENV: production
  secrets:
    - RAILS_MASTER_KEY

servers:
  web:
    hosts:
      - "49.13.224.98"
    options:
      memory: 512M

  job:
    hosts:
      - "49.13.224.98"
    options:
      memory: 512M
    cmd: bundle exec sidekiq -C config/sidekiq.yml

env:
  clear:
    RAILS_LOG_TO_STDOUT: 1
    RAILS_SERVE_STATIC_FILES: 1
    RAILS_ENV: production
  secret:
    - RAILS_MASTER_KEY

accessories:
  postgres:
    image: postgres:18.0
    hosts:
      - "49.13.224.98"
    env:
      clear:
        POSTGRES_DB: rubycrow_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - pg_data:/var/lib/postgresql

  redis:
    image: redis:8.0
    hosts:
      - "49.13.224.98"
    cmd: "/bin/sh -c 'redis-server --requirepass $REDIS_PASSWORD' --replica-read-only no"
    env:
      secret:
        - REDIS_PASSWORD
    directories:
      - redis_data:/data

proxy:
  ssl: false
  app_port: 3000
  forward_headers: true
  host: "rubycrow.dev"
  healthcheck:
    interval: 3
    path: /up
    timeout: 3
  logging:
    request_headers:
      - Cache-Control
      - X-Forwarded-Proto
    response_headers:
      - X-Request-ID
      - X-Request-Start

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
