---
:verbose: false
:concurrency: 10
:timeout: 25

:queues:
  - critical
  - default
  - <%= `hostname`.strip %>
  - low

development:
  :concurrency: 10
production:
  :concurrency: 10
staging:
  :concurrency: 15
